### ISSUE TITLE
changes of object in a stapes instance won't tirgger events

### ISSUE THREAD

**Issue by AmBeta** [hay/stapes#69]
The codes below won't trigger an update or change event on `dog` as expected.

```
var Dog = Stapes.subclass();

var dog = new Dog();
dog.set('cat', []);

var cat = dog.get('cat').push('Tom');
dog.set('cat', cat);
```

As I go through the Stapes code, I find that the `cat` in `dog` has already changed when I did the `push` action.

**Comment by hay** [comment]
I'm not quite sure what the problem is. When you add an event listener to your code, for example like this:

    var Dog = Stapes.subclass();
    var dog = new Dog();

    dog.set('cat', []);

    dog.on('change:cat', function() {
        console.log('cat is now:' + dog.get('cat'));
    })

I see the events logging as intended. Note that the value of `cat` is 1 (that's the return value of the `push` function), it's not an array with the content `['Tom']` as you might expect.
